# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/offerpilot}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 5000
    password: ${REDIS_PASSWORD:}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: ${KNIFE4J_USERNAME:root}
    password: ${KNIFE4J_PASSWORD:}

hotkey:
  etcd-server: ${HOTKEY_ETCD_SERVER:http://localhost:2379}

langchain4j:
  open-ai:
    chat-model:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${AI_API_KEY:}
      model-name: ${AI_MODEL_NAME:qwen-plus}
